kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: store-solrcluster
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=8983
  - gid=8983
parameters:
  skuName: Premium_LRS
#  location: eastus
#  storageAccount: azure_storage_account_name
