apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-volume
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
    pv.beta.kubernetes.io/uid: "1000"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk: 
    fsType: "ext4" 
    pdName: "pd-disk-solr"

