apiVersion: v1
kind: Service
metadata:
  name: solr-service-hs
  labels:
    app: solr-app
spec:
  ports:
  - port: 32080
  clusterIP: None
  selector:
    app: solr-app
---
apiVersion: v1
kind: Service
metadata:
  name: solr-service
spec:
  ports:
  - port: 32080
    targetPort: 32080
    nodePort: 32080
    protocol: TCP
  selector:
    app: solr-app
  type: NodePort
