kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: store-zkensemble
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  fsType: ext4
  type: gp2
volumeBindingMode: WaitForFirstConsumer
